name: Deploy 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test

      - name: Upload JAR artifact
        if: success()  # Upload artifact only if build and tests pass
        uses: actions/upload-artifact@v2
        with:
          name: tictactoe
          path: target/tictactoe.jar  # Adjust the path if necessary

      - name: Create Release
        if: success()  # Create release only if build and tests pass
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  
        with:
          tag_name: v1.0.2  # Use a unique tag name for each release
          release_name: Release v1.0.1 
          body: Release of version 1.0.1

      - name: Upload Release Asset
        if: success()  # Upload asset only if release creation is successful
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/tictactoe.jar  # Adjust the path if necessary
          asset_name: tictactoe.jar
          asset_content_type: application/java-archive
