name: maven

on:
  push:
    branches:
      - main
      - feature/Player
      - feature/Game
      - feature/Board
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Upload JAR file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-application
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v2
      with:
        name: my-application
        path: .

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }} # Example: v1, v2, v3, ...
        release_name: Release ${{ github.run_number }} # Example: Release 1, Release 2, Release 3, ...
        body: |
          Release notes can be added here.
        draft: false
        prerelease: false

    - name: Upload JAR to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/*.jar
        asset_name: my-application.jar
        asset_content_type: application/java-archive
